### ISSUE TITLE
SMTP - Email as Username Not Working

### ISSUE THREAD

**Issue by andrew-from-toronto** [containrrr/shoutrrr#103]
I am trying to use shotrrr via the scrutiny project to send notifications over SMTP. Problem I am having is that my SMTP provider Mailgun issues usernames as an email address. However it seems that due to the format and my username having an @ symbol in it something is not working correctly. Here's the issue on that project: https://github.com/AnalogJ/scrutiny/issues/129

Let me know if I can provide any more information here, thanks.

**Comment by piksel** [comment]
The @-symbol need to be URL-escaped. You can use `shoutrrr generate` to have it do this for you:
```
$ shoutrrr generate smtp
Generating URL for smtp using basic generator
Enter the configuration values as prompted
```
```yaml
Host: senderhost.com
Username: user@mailhost.com
Password: pass
Port[25]:
FromAddress: bot@senderhost.com
FromName: Mailbot
ToAddresses: recipient@mailhost.com
Subject[Shoutrrr Notification]:
Auth: Plain
Encryption[Auto]:
UseStartTLS[Yes]:
UseHTML[No]:

URL: smtp://user%40mailhost.com:pass@senderhost.com:25/?auth=Plain&encryption=Auto&fromaddress=bot@senderhost.com&fromname=Mailbot&starttls=Yes&subject=Shoutrrr Notification&toaddresses=recipient@mailhost.com&usehtml=No
```

Or, you can just simply replace the @ in your username with `%40`. 😁
