### ISSUE TITLE
[USAGE HELP] Getting Shoutrr to Work in Docker

### ISSUE THREAD

**Issue by mokshmridul** [containrrr/shoutrrr#195]
Hi Guys,

Let me start of by saying what an amazing project this is. I came across this from Watchtower, where im now using it for my notifications.

I have managed to get it running in CLI mode, but i recently discovered that it can be run in Docker as well, and i would like to get it up and running from there, rather than CLI. I am however unable to understand how to get the notifications running (once i get the docker image setup)

Any help / guidance on this would be very highly appreciated.

Thank You :)

PS: My extracted Docker Compose is below:

````
  shoutrrr:
    image: containrrr/shoutrrr
    container_name: shoutrrr
    environment:
      - TZ=Asia/Kolkata
    restart: unless-stopped
````
