### ISSUE TITLE
shoutrrr timed out on same machine with traefik (docker)

### ISSUE THREAD

**Issue by seagullki** [containrrr/shoutrrr#219]
**PC1 (docker: traefik,gotify, ...)**
_curl ok | shoutrrr fails_

docker run containrrr/shoutrrr send gotify://<FQDN>/<TOKEN>?title=Test "hello world"
-> Error: failed to send using gotify: timed out

curl "https://<FQDN>/message?token=<TOKEN>" -F "title=Test" -F "message=hello world" -F "priority=5"
-> {"id":3,"appid":4,"message":"hello world","title":"Test","priority":5,"date":"2021-12-18T16:44:05.121021101+01:00"}

The same problem with: Watchtower and uptime-kuma
watchtower-24h_auto | Failed to send notification via shoutrrr (url=gotify://<FQDN>/<TOKEN>?title=Watchtower+updates+on+b814354bf48a):  failed to send using gotify: timed out

**PC2**
_curl ok | shoutrrr ok_
docker run containrrr/shoutrrr send gotify://<FQDN>/<TOKEN>?title=Test "hello world"
-> Notification sent

-> curl, watchtower und uptime-kuma okay too

But on the same PC no way to use shoutrrr. But Watchtower an other use shutrrr.

**My docker config:**
```yaml
version: '3.5'

## *****************************************************************************************
## ** Services
## *****************************************************************************************
services:

## *****************************************************************************************
  traefik:
    image: traefik:latest
    container_name: traefik
    environment:
      - TZ=Europe/Berlin
    command:
      - --log=true
      - --log.level=${TRAEFIK_LOGLEV}
      - --api
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false

      - --entrypoints.http=true
      - --entrypoints.http.address=:80
      - --entrypoints.http.http.redirections.entrypoint.to=https
      - --entrypoints.http.http.redirections.entrypoint.scheme=https

      - --entrypoints.https=true
      - --entrypoints.https.address=:443

      - --certificatesResolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesResolvers.letsencrypt.acme.storage=/etc/traefik/acme.json
      - --certificatesResolvers.letsencrypt.acme.httpChallenge.entryPoint=http

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
    labels:
      # WebGui Aufruf über FQDN durch Traefik mit https und Let's Encrypt Zertifikat
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`${TRAEFIK_FQDN}`)
      - traefik.http.routers.api.entrypoints=https
      - traefik.http.routers.api.entrypoints
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=letsencrypt
      # WebGui durch Authelia abgesichert
      - traefik.http.routers.api.middlewares=authelia@docker
      # automatisches Update (pull und Neustart) per Watchtower
      - com.centurylinklabs.watchtower.enable=true
      - com.centurylinklabs.watchtower.scope=24h_auto

    restart: unless-stopped

## *****************************************************************************************
  authelia:
...

## *****************************************************************************************
  gotify:
    image: gotify/server
    container_name: gotify
    environment:
      - TZ=Europe/Berlin
      - GOTIFY_SERVER_PORT=80
      - GOTIFY_SERVER_KEEPALIVEPERIODSECONDS=0
      - GOTIFY_SERVER_SSL_ENABLED=false

      - GOTIFY_SERVER_STREAM_PINGPERIODSECONDS=45
      - GOTIFY_DATABASE_DIALECT=sqlite3
      - GOTIFY_DATABASE_CONNECTION=data/gotify.db
      - GOTIFY_DEFAULTUSER_NAME=admin
      - GOTIFY_DEFAULTUSER_PASS=admin
      - GOTIFY_PASSSTRENGTH=10
      - GOTIFY_UPLOADEDIMAGESDIR=data/images
      - GOTIFY_PLUGINSDIR=data/plugins
      - GOTIFY_REGISTRATION=false
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./gotify/data:/app/data
    networks:
      - traefik
    expose:
      - 80
    labels:
      # WebGui Aufruf über FQDN durch Traefik mit https und Let's Encrypt Zertifikat
      - traefik.enable=true
      - traefik.http.routers.gotify.rule=Host(`${GOTIFY_FQDN}`)
      - traefik.http.routers.gotify.entrypoints=https
      - traefik.http.routers.gotify.tls=true
      - traefik.http.routers.gotify.tls.certresolver=letsencrypt
      # automatisches Update (pull und Neustart) per Watchtower
      - com.centurylinklabs.watchtower.enable=true
      - com.centurylinklabs.watchtower.scope=24h_auto
    depends_on:
      - traefik
    restart: unless-stopped

## *****************************************************************************************
  watchtower:
...

## *****************************************************************************************
  uptime-kuma:
...

## *****************************************************************************************
## ** networks
## *****************************************************************************************
networks:

  traefik:
    name: "traefik"
    driver: bridge

  abakus_base:
    name: "abakus_base"
    driver: bridge
```

Someone an idea for me?
