### ISSUE TITLE
Cannot send messages through SMTP servers requiring non-generic client hosts

### ISSUE THREAD

**Issue by arjundhanjal** [containrrr/shoutrrr#270]
I'm trying to use Gmail's [SMTP relay](https://support.google.com/a/answer/2956491?hl=en) in Watchtower (via Shoutrrr) to send email notifications, but when I do, I get the following error:

```
time="2022-10-12T16:47:39-04:00" level=error msg="Failed to send shoutrrr notification" error="error authenticating: EOF" index=0 notify=no service=smtp
```

Here's my config:

```yaml
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - PUID=1003
      - PGID=1004
      - TZ=America/Toronto
      - WATCHTOWER_SCHEDULE=0 */30 4-16 * * *
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=watchtower@domain.ca
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=me@domain.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp-relay.gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=me@domain.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=MyPassword
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
```

I ran the same config through the Shoutrrr CLI and got the following output:

```sh
[~] # docker run --rm- it containerrr/shoutrrr send -v "smtp://me%40domain.com:MyPassword@smtp-relay.gmail.com:587/?auth=Plain&encryption=Auto&fromaddress=watchtower@domain.ca&fromname=Watchtower&starttls=Yes&toaddresses=me@domain.com&usehtml=No" TestMessage
URLs: smtp://me%domain.com:MyPassword@smtp-relay.gmail.com:587/?auth=Plain&encryption=Auto&fromaddress=watchtower@domain.ca&fromname=Watchtower&starttls=Yes&toaddresses=me@domain.com&usehtml=No
Message: TestMessage
SHOUTRRR 2022/10/12 20:55:14 Warning: StartTLS enabled, but server did not report support for it. Connection is NOT encrypted
```

This is unexpected behaviour, because Gmail's SMTP relay definitely supports StartTLS and the same SMTP configurations work in other applications.

I've tried the following permutations and they all result with the same `error authenticating: EOF` response:
- port 587, StartTLS enabled, encryption Auto
- port 587, StartTLS enabled, encryption ExplicitTLS
- port 465, StartTLS disabled, encryption Auto
- port 465, StartTLS disabled, encryption ImplicitTLS

After doing some research online, I've seen that some SMTP libraries (e.g., go-smtp) send an initial HELO localhost message prior to sending the expected message (sorry for being vague here, SMTP/their machinations aren't my wheelhouse) and this initial HELO localhost call is what breaks StartTLS. All of that being said, though, if that were the issue, I should have been able to authenticate using SSL/port 465 with StartTLS disabled.

Looking for some guidance here. Happy to provide additional details if needed.
