### ISSUE TITLE
ntfy.sh without https

### ISSUE THREAD

**Issue by Karta775** [containrrr/shoutrrr#437]
Hi, I host a ntfy.sh instance on my server and access it myself via reverse proxy. My other services access locally via http. My docker-compose.yml for watchtower looks like this:

```yml
version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - PUID=1029
      - PGID=1030
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=ntfy://ntfy-sh/watchtower?title=Watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - ntfy-sh

networks:
  ntfy-sh:
    external: true
```

My watchtower logs:
```txt
time="2024-02-05T21:55:04Z" level=info msg="Watchtower 1.7.1"
time="2024-02-05T21:55:04Z" level=info msg="Using notifications: ntfy"
time="2024-02-05T21:55:04Z" level=info msg="Checking all containers (except explicitly disabled with label)"
time="2024-02-05T21:55:04Z" level=info msg="Scheduling first run: 2024-02-06 21:55:04 +0000 UTC"
time="2024-02-05T21:55:04Z" level=info msg="Note that the first check will be performed in 23 hours, 59 minutes, 59 seconds"
time="2024-02-05T21:55:04Z" level=error msg="Failed to send shoutrrr notification" error="failed to send ntfy notification: error sending payload: Post \"https://ntfy-sh/watchtower\": dial tcp 172.24.0.3:443: connect: connection refused" index=0 notify=no service=ntfy
```

My best guess is that watchtower/shoutrrr is attempting connect to my ntfy.sh instance exclusively over HTTPS which isn't set up locally.

Thanks
