### ISSUE TITLE
Telegram notificatios timing out - failed to send using telegram: timed out

### ISSUE THREAD

**Issue by aronmgv** [containrrr/shoutrrr#454]
Hello,

I am trying to configure watchtower but getting `failed to send using telegram: timed out` no matter what configuration I use for `WATCHTOWER_NOTIFICATION_URL`.

```yml
services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_TIMEOUT=30s
      - WATCHTOWER_NOTIFICATION_URL=telegram://111:222@telegram?chats=333&preview=No
      - WATCHTOWER_SCHEDULE=0 * * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
```

```
watchtower  | time="2025-02-09T20:40:36Z" level=info msg="Watchtower 1.7.1"
watchtower  | time="2025-02-09T20:40:36Z" level=info msg="Using notifications: telegram"
watchtower  | time="2025-02-09T20:40:36Z" level=info msg="Only checking containers using enable label"
watchtower  | time="2025-02-09T20:40:36Z" level=info msg="Scheduling first run: 2025-02-09 20:40:43 +0000 UTC"
watchtower  | time="2025-02-09T20:40:36Z" level=info msg="Note that the first check will be performed in 6 seconds"
watchtower  | time="2025-02-09T20:40:46Z" level=error msg="Failed to send shoutrrr notification" error="failed to send using telegram: timed out" index=0 notify=no service=telegram
```

I tried every single possible configuration for `WATCHTOWER_NOTIFICATION_URL` still no luck :/

Then I found one user posting it is possible to get this URL generated via: `docker run --rm -it containrrr/shoutrrr generate telegram` which I did and it gave the the following URL format: `telegram://111:222@telegram?chats=333&preview=No`. This is when I want to send notifications to the bot chat directly (yes i started conversation with bot prior)..
I tried using private channel with same time out error.. 

I tested it directly using `containrrr/shoutrrr:latest` and sending commnad:

```
docker run --rm containrrr/shoutrrr:latest send telegram://111:222@telegram?chats=333 "Test message from Shoutrrr"
failed to send using telegram: timed out
```

I confirm bot is configured correctly sich I get message via POST:

```
curl -X POST "https://api.telegram.org/bot111:222/sendMessage" -d "chat_id=333&text=Test"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   312  100   285  100    27   2241    212 --:--:-- --:--:-- --:--:--  2516{"ok":true,"result":{"message_id":2,"from":{"id":111,"is_bot":true,"first_name":"WATCHTOWER.example.com","username":"example_watchtower_bot"},"chat":{"id":333,"first_name":"ZZZ","last_name":"ZZZ","username":"example","type":"private"},"date":1739135500,"text":"Test"}}
```

![Image](https://github.com/user-attachments/assets/fa1ea6a5-dc8d-462f-b9ff-c80cd55e6623)

What am I doing wrong? Thanks!
