### ISSUE TITLE
teams webhook 403

### ISSUE THREAD

**Issue by JPRauwolf** [containrrr/shoutrrr#458]
Hi,
I'm trying to configure a teams webhook running on the watchtower:latest docker image.
The webhook created has the following form:
`https://<organization>.webhook.office.com/webhookb2/<abc-abc-abc>@<def-def-def>/IncomingWebhook/<xxxx>/<yyyy>/<zzzz>`
from the documentation I know that it should be like this:
`https://<organization>.webhook.office.com/webhookb2/<group>@<tenant>/IncomingWebhook/<altId>/<groupOwner>`
The first parts `organization`, `group` and `tenant` are obvious but I dont know how to split the `<xxxx>/<yyyy>/<zzzz>` parts into  `<altId>/<groupOwner>`.
As the final URL `teams://group@tenant/altId/groupOwner?host=organization.webhook.office.com` has altId and groupOwner in the same order I just substituted it for the `<xxxx>/<yyyy>/<zzzz>` part.
That returns a 403 error. 

If I try using `<xxxx>/<yyyy>/<zzzz>` I get a 403.
If I try only using `<xxxx>/<yyyy>` I also get a 403.
If I try only using `<xxxx>/<zzzz>` I get an error that the token is incomplete.
If I try only using `<yyyy>/<zzzz>` I get an error that the third token part is invalid.

I did a sanity check and using curl and the same link the webhook works.

my `compose.yaml` looks the following
```
services:
  monitor:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=<url>
```

Is there any configuration I do wrong?
Best regards Jan Philipp
